theme: jekyll-theme-cayman

title: Victor Blog
description: Talk is cheap. Show me the code
url: https://viper140.github.io/
email: 1401644339@qq.com

# 显示在浏览器上搜索的时候显示的标题
SEOTitle: 维克多博客 | Victor Blog

# markdown: kramdown
# header-img: img/post-bg-rwd.jpg # 首页背景图片
# permalink: /:title.html
# feed: /atom.xml
# baseurl: ""
# lsi: true
# rouge: true
# safe: true

author:
  name: Victor
  nickname: Victor
  site: https://viper140.github.io/

seo:
  keyword:
  description: